import React from 'react';
import { Layer } from 'react-mapbox-gl';

const SettlementLabel: React.FC = () => (
  <Layer
    layout={{
      'text-line-height': 1.1,
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.2, 0, 0.9, 1],
        ['zoom'],
        3,
        [
          'step',
          ['get', 'symbolrank'],
          12,
          9,
          11,
          10,
          10.5,
          12,
          9.5,
          14,
          8.5,
          16,
          6.5,
          17,
          4,
        ],
        15,
        [
          'step',
          ['get', 'symbolrank'],
          28,
          9,
          26,
          10,
          23,
          11,
          21,
          12,
          20,
          13,
          19,
          15,
          17,
        ],
      ],
      'icon-image': [
        'case',
        ['==', ['get', 'capital'], 2],
        'border-dot-13',
        ['step', ['get', 'symbolrank'], 'dot-11', 9, 'dot-10', 11, 'dot-9'],
      ],
      'text-font': [
        'step',
        ['zoom'],
        ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        8,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          11,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        10,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          12,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        11,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          13,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        12,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          15,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        13,
        ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
      ],
      'text-justify': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'text_anchor'],
          ['bottom', 'top'],
          'center',
          ['left', 'bottom-left', 'top-left'],
          'left',
          ['right', 'bottom-right', 'top-right'],
          'right',
          'center',
        ],
        8,
        'center',
      ],
      'text-offset': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'capital'],
          2,
          [
            'match',
            ['get', 'text_anchor'],
            'bottom',
            ['literal', [0, -0.3]],
            'bottom-left',
            ['literal', [0.3, -0.1]],
            'left',
            ['literal', [0.45, 0.1]],
            'top-left',
            ['literal', [0.3, 0.1]],
            'top',
            ['literal', [0, 0.3]],
            'top-right',
            ['literal', [-0.3, 0.1]],
            'right',
            ['literal', [-0.45, 0]],
            'bottom-right',
            ['literal', [-0.3, -0.1]],
            ['literal', [0, -0.3]],
          ],
          [
            'match',
            ['get', 'text_anchor'],
            'bottom',
            ['literal', [0, -0.25]],
            'bottom-left',
            ['literal', [0.2, -0.05]],
            'left',
            ['literal', [0.4, 0.05]],
            'top-left',
            ['literal', [0.2, 0.05]],
            'top',
            ['literal', [0, 0.25]],
            'top-right',
            ['literal', [-0.2, 0.05]],
            'right',
            ['literal', [-0.4, 0.05]],
            'bottom-right',
            ['literal', [-0.2, -0.05]],
            ['literal', [0, -0.25]],
          ],
        ],
        8,
        ['literal', [0, 0]],
      ],
      'text-anchor': ['step', ['zoom'], ['get', 'text_anchor'], 8, 'center'],
      'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
      'text-max-width': 7,
    }}
    maxZoom={15}
    filter={[
      'all',
      ['<=', ['get', 'filterrank'], 3],
      ['==', ['get', 'class'], 'settlement'],
      [
        'step',
        ['zoom'],
        true,
        13,
        ['>=', ['get', 'symbolrank'], 11],
        14,
        ['>=', ['get', 'symbolrank'], 13],
      ],
    ]}
    type="symbol"
    source="composite"
    id="settlement-label"
    paint={{
      'text-color': 'hsl(0, 0%, 0%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1,
      'icon-opacity': ['step', ['zoom'], 1, 8, 0],
      'text-halo-blur': 1,
    }}
    sourceLayer="place_label"
  />
);

export default SettlementLabel;
